### ISSUE TITLE
GUI needs an overhaul

### ISSUE THREAD

**Issue by nohal** [Rasbats/otcurrent_pi#9] opened 2018-02-02 18:53 UTC
The GUI of the plugin deserves a bit more care and love to provide an acceptable user experience...
<img width="674" alt="screen shot 2018-02-02 at 15 35 46" src="https://user-images.githubusercontent.com/249856/35749614-eac50618-0830-11e8-9062-62a9400f9d50.png">

Can you please add the FBP project to the repository to start with without having to recreate it from scratch?

**Comment by rgleason** [comment] 2018-02-02 23:15
Mike, didn't we work in the fpb?  I think I did some adjustment and sent it to you via email. I've looked in my emails on this machine, and don't have the fpb, but it might be in my other machine. Won't have access to it for another 2.5 weeks however...  Will keep looking.  I deleted my local repos unfortunately but that would also be on the other machine. I am not sure we used the normal git push process. Maybe that is the cause of this?  I think you emailed me the fpb and I emailed it back.

**Comment by rgleason** [comment] 2018-02-02 23:20
Proportion of text box for date/time set to 100

—
You are receiving this because you are subscribed to this thread.
View it on GitHub or mute the thread.

https://github.com/Rasbats/otcurrent_pi/releases/tag/v1.3

https://github.com/Rasbats/otcurrent_pi/commit/6eb4728229196fd5636a9a139d42067185118c8e


Tried a github search of the repos on  fbp  and nothing came up.

**Comment by Rasbats** [comment] 2018-02-03 08:38
Rick ... Other plugins but not otcurrent fpb.

**Comment by Rasbats** [comment] 2018-02-04 08:01
Re-built the .fbp and added it to the 1.4 release. 

Moving to API 15 has stopped it working with OpenCPN 4.8.0 (I think). Or is this just because of the ocpn_plugin.h found on GitHub? Is there a solution to allow backward compatibility?

Intend adding pc timezone to the date/time shown before making another release.

**Comment by nohal** [comment] 2018-02-04 13:53
> Moving to API 15 has stopped it working with OpenCPN 4.8.0 (I think). Or is this just because of the ocpn_plugin.h found on GitHub? Is there a solution to allow backward compatibility?

Yes, as described in #8 description, it moves the compatibility level to O4.8.2 where the physical screen size API is added.

If you want to make a release compatible with older versions, simply do it without commit https://github.com/Rasbats/otcurrent_pi/commit/7b73add8f634b7cb1405b731a2c2878607f85887

**Closed as completed** 2018-02-04 18:50 UTC
